import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import worker from '../worker/index.js';
const origin='https://tracker.example';
const rows=new Map();
const DB={prepare(sql){return{bind(...args){return{async first(){return rows.has(args[0])?{data:rows.get(args[0])}:null},async run(){assert.match(sql,/INSERT INTO tracker_state/);rows.set(args[0],args[1]);return{success:true}}}}}}};
const first=await worker.fetch(new Request(origin+'/api/state'),{DB});assert.equal(first.status,200);const cookie=first.headers.get('set-cookie').split(';')[0];assert.match(cookie,/aion_profile=/);
const state={checks:{'daily:main:duties':true,'route:0':true},settings:{hour:0,day:3,auto:false},periods:{}};
const request=(data,requestOrigin=origin)=>new Request(origin+'/api/state',{method:'PUT',headers:{cookie,origin:requestOrigin,'Content-Type':'application/json'},body:JSON.stringify(data)});
assert.equal((await worker.fetch(request(state),{DB})).status,200);
assert.deepEqual(await (await worker.fetch(new Request(origin+'/api/state',{headers:{cookie}}),{DB})).json(),state);
assert.equal((await worker.fetch(request(state,'https://other.example'),{DB})).status,403);
assert.equal((await worker.fetch(request({...state,settings:{hour:24,day:3,auto:false}}),{DB})).status,400);
assert.equal((await worker.fetch(new Request(origin+'/api/state'),{})).status,503);
assert.equal((await worker.fetch(new Request(origin+'/missing'),{DB})).status,404);
const html=await (await worker.fetch(new Request(origin),{DB})).text();
const window=new Window({url:origin,settings:{enableJavaScriptEvaluation:true}});let stored=null,saves=0,fail=false;
window.fetch=async(path,opts)=>{if(opts?.method==='PUT'){saves++;if(fail)return{ok:false};stored=JSON.parse(opts.body);return{ok:true}}return{ok:true,json:async()=>stored}};
window.document.write(html);await new Promise(r=>setTimeout(r,30));
const doc=window.document;assert.equal(doc.querySelectorAll('.step').length,9);assert.match(doc.getElementById('status').textContent,/loaded/);
doc.querySelector('[data-view="daily"]').click();assert.equal(doc.querySelectorAll('.task').length,8);
const input=doc.getElementById('check-duties');input.checked=true;input.dispatchEvent(new window.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,250));assert.equal(stored.checks['daily:main:duties'],true);
doc.getElementById('character').value='alt1';doc.getElementById('character').dispatchEvent(new window.Event('change'));assert.equal(doc.getElementById('check-duties').checked,false);
doc.querySelector('[data-view="weekly"]').click();assert.equal(doc.querySelectorAll('.task').length,7);
doc.querySelector('[data-view="qa"]').click();assert.equal(doc.querySelectorAll('.qa-grid article').length,8);
doc.querySelector('[data-view="launch"]').click();assert.equal(doc.querySelectorAll('.day').length,3);
doc.querySelector('[data-view="route"]').click();let route=doc.querySelector('[data-group="route"]');route.checked=true;route.dispatchEvent(new window.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,250));assert.equal(stored.checks['route:0'],true);assert.equal(doc.getElementById('route-count').textContent,'1 / 9');
stored.settings.auto=true;stored.periods={daily:'2020-01-01',weekly:'2020-01-01'};const resetWindow=new Window({url:origin,settings:{enableJavaScriptEvaluation:true}});resetWindow.fetch=window.fetch;resetWindow.document.write(html);await new Promise(r=>setTimeout(r,30));assert.equal(stored.checks['daily:main:duties'],undefined);assert.equal(stored.checks['route:0'],true);await resetWindow.happyDOM.abort();resetWindow.close();
fail=true;route=doc.querySelector('[data-group="route"]');route.checked=false;route.dispatchEvent(new window.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,250));assert.match(doc.getElementById('status').textContent,/Could not save/);assert.equal(doc.getElementById('retry').hidden,false);
fail=false;doc.getElementById('retry').click();await new Promise(r=>setTimeout(r,30));assert.match(doc.getElementById('status').textContent,/saved/);assert.ok(saves>=4);
await window.happyDOM.abort();window.close();console.log('Passed: API persistence, validation, isolation, all views, checklist saving, automatic resets, and save-failure retry.');
