import assert from 'node:assert/strict';
import { Window } from 'happy-dom';
import { readFile } from 'node:fs/promises';
const origin='https://tracker.example',storageKey='aion2-progress-tracker-v2';
let html=await readFile(new URL('../site/index.html',import.meta.url),'utf8');
const sourceScripts=await Promise.all(['data.js','schedules.js','app.js'].map(name=>readFile(new URL('../site/'+name,import.meta.url),'utf8')));
html=html.replace('<script src="./data.js" defer></script><script src="./schedules.js" defer></script><script src="./app.js" defer></script>',()=>'<script>'+sourceScripts.join('\n')+'\nwindow.timerTest={nextTimerTimes,timerCountdown,activeTimerWindow,nextWeeklyReset,parseTimerTimes,defaultTimerSchedule,germanyDailyResetTime};'+'</script>').replace('<link rel="stylesheet" href="./styles.css">','');
const pause=()=>new Promise(r=>setTimeout(r,40));const windows=[];
async function open(saved){const w=new Window({url:origin,settings:{enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true}});windows.push(w);const requests=[];w.fetch=async(...args)=>{requests.push(args);throw Error('Static tracker must not use a backend')};if(saved!==undefined)w.localStorage.setItem(storageKey,typeof saved==='string'?saved:JSON.stringify(saved));w.document.write(html);await pause();return{w,d:w.document,requests}}
const {w,d,requests}=await open();assert.equal(d.getElementById('daily-count').textContent,'0 / 9');assert.equal(d.getElementById('weekly-count').textContent,'0 / 8');assert.equal(d.querySelectorAll('.step').length,12);assert.equal(d.querySelectorAll('#character option').length,4);assert.match(d.getElementById('status').textContent,/Saved in this browser/);
d.getElementById('character-ilvl').value='1900.5';d.getElementById('character-ilvl').dispatchEvent(new w.Event('change'));assert.equal(JSON.parse(w.localStorage.getItem(storageKey)).itemLevels.main,1900.5);d.querySelector('[data-view="daily"]').click();assert.deepEqual([...d.querySelectorAll('.checklist-group h3')].map(e=>e.textContent),['Daily','Scheduled','Routine']);assert.match(d.querySelector('#check-festival').closest('.task').textContent,/Daevanion Crystals first, then Stigma Shards/);assert.equal(d.querySelector('#check-festival').closest('.checklist-group').getAttribute('aria-label'),'Daily tasks');assert.match(d.querySelector('#check-festival').closest('.task').textContent,/don’t need to use all entries in one day/);let input=d.getElementById('check-duties');input.checked=true;input.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(JSON.parse(w.localStorage.getItem(storageKey)).checks['daily:main:duties'],true);assert.equal(d.getElementById('daily-count').textContent,'1 / 9');assert.equal(d.getElementById('daily-next').textContent,'Complete affordable supply requests');assert.equal(d.getElementById('daily-progress').getAttribute('aria-valuenow'),'1');d.getElementById('open-weekly').click();assert.equal(d.getElementById('tab-weekly').getAttribute('aria-selected'),'true');d.querySelector('[data-view="daily"]').click();
const restored=await open(w.localStorage.getItem(storageKey));assert.equal(restored.requests.length,0);assert.equal(restored.d.getElementById('character-ilvl').value,'1900.5');restored.d.querySelector('[data-view="daily"]').click();assert.equal(restored.d.getElementById('check-duties').checked,true);
d.getElementById('manage-characters').click();d.getElementById('main-name').value='<img src=x onerror=alert(1)>';d.getElementById('alt-count').value='6';d.getElementById('alt-count').dispatchEvent(new w.Event('input'));d.getElementById('alt-name-6').value='My sixth alt';d.getElementById('alt-ilvl-6').value='2100';d.getElementById('characters-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelectorAll('#character option').length,7);assert.equal(d.getElementById('character').textContent.includes('My sixth alt'),true);assert.equal(d.getElementById('character').querySelector('img'),null);
d.getElementById('character').value='alt6';d.getElementById('character').dispatchEvent(new w.Event('change'));assert.equal(d.getElementById('daily-count').textContent,'0 / 9');assert.equal(d.getElementById('daily-character').textContent,'My sixth alt');assert.equal(d.getElementById('character-ilvl').value,'2100');input=d.getElementById('check-duties');input.checked=true;input.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(JSON.parse(w.localStorage.getItem(storageKey)).checks['daily:alt6:duties'],true);
function count(n){d.getElementById('manage-characters').click();d.getElementById('alt-count').value=String(n);d.getElementById('alt-count').dispatchEvent(new w.Event('input'));d.getElementById('characters-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))}
count(0);assert.equal(d.querySelectorAll('#character option').length,1);assert.equal(d.getElementById('character').value,'main');count(6);d.getElementById('character').value='alt6';d.getElementById('character').dispatchEvent(new w.Event('change'));assert.equal(d.getElementById('check-duties').checked,true);assert.equal(d.getElementById('character').textContent.includes('My sixth alt'),true);assert.equal(d.getElementById('character-ilvl').value,'2100');
let exported;w.URL.createObjectURL=blob=>{exported=blob;return'blob:backup'};w.URL.revokeObjectURL=()=>{};d.getElementById('export-data').click();assert.ok(exported);const backup=JSON.parse(await exported.text());assert.equal(backup.format,'aion2-progress-tracker');assert.equal(backup.state.characters.altCount,6);assert.deepEqual(backup.state.itemLevels,{main:1900.5,alt6:2100});
async function importFile(payload){const file=new w.File([typeof payload==='string'?payload:JSON.stringify(payload)],'backup.json',{type:'application/json'});Object.defineProperty(d.getElementById('import-file'),'files',{value:[file],configurable:true});d.getElementById('import-file').dispatchEvent(new w.Event('change'));await pause()}
const before=w.localStorage.getItem(storageKey);await importFile('{bad json');assert.equal(w.localStorage.getItem(storageKey),before);assert.match(d.getElementById('status').textContent,/Import rejected/);
await importFile({...backup,state:{...backup.state,characters:{main:'Bad',altCount:51,alts:[]}}});assert.equal(w.localStorage.getItem(storageKey),before);
await importFile({...backup,state:{...backup.state,itemLevels:{main:-1}}});assert.equal(w.localStorage.getItem(storageKey),before);
backup.state.characters.main='Imported main';await importFile(backup);assert.equal(d.getElementById('import-dialog').open,true);d.getElementById('cancel-import').click();assert.equal(w.localStorage.getItem(storageKey),before);
await importFile(backup);d.getElementById('confirm-import').click();assert.equal(JSON.parse(w.localStorage.getItem(storageKey)).characters.main,'Imported main');assert.equal(d.getElementById('character').textContent.includes('Imported main'),true);assert.equal(d.getElementById('character-ilvl').value,'1900.5');
const expired={...backup.state,settings:{hour:0,day:3,auto:true},periods:{daily:'2020-01-01',weekly:'2020-01-01'}};expired.checks['route:0']=true;const reset=await open(expired);const resetData=JSON.parse(reset.w.localStorage.getItem(storageKey));assert.equal(resetData.checks['daily:main:duties'],undefined);assert.equal(resetData.checks['route:0'],true);assert.deepEqual(resetData.itemLevels,backup.state.itemLevels);
const guideChecks=await open({checks:{'daily:main:festival':true,'weekly:main:nightmare':true,'weekly:main:daily-dungeon':true},settings:{hour:0,day:3,auto:false},periods:{}});
guideChecks.d.querySelector('[data-view="daily"]').click();assert.match(guideChecks.d.getElementById('check-festival').closest('.task').textContent,/2 keys\/day/);assert.equal(guideChecks.d.getElementById('check-festival').checked,true);assert.match(guideChecks.d.getElementById('check-duties').closest('.task').textContent,/Server-wide/);
guideChecks.d.querySelector('[data-view="weekly"]').click();assert.equal(guideChecks.d.getElementById('check-nightmare').checked,true);assert.equal(guideChecks.d.getElementById('check-nightmare').closest('.checklist-group').getAttribute('aria-label'),'Accumulating tasks');assert.match(guideChecks.d.getElementById('check-nightmare').closest('.task').textContent,/Accumulating, not a weekly reset/);assert.equal(guideChecks.d.getElementById('check-daily-dungeon').checked,true);assert.match(guideChecks.d.getElementById('check-daily-dungeon').closest('.task').textContent,/14 entries\/week/);assert.equal(guideChecks.d.querySelectorAll('.task').length,8);
const originalProgress=await open({checks:{'route:2':true,'route:3':true,'route:8':true},settings:{hour:0,day:3,auto:false},periods:{}});
assert.equal(originalProgress.d.getElementById('character-ilvl').value,'');assert.equal(originalProgress.d.querySelector('[data-id="2"]').checked,true);
assert.match(originalProgress.d.querySelector('[data-id="2"]').closest('.step').textContent,/Claim the guaranteed Vakron armor/);
assert.equal(originalProgress.d.querySelector('[data-id="3"]').checked,true);
assert.equal(originalProgress.d.querySelector('[data-id="9"]').checked,false);
assert.equal(originalProgress.d.querySelector('[role=progressbar]').getAttribute('aria-valuemax'),'12');
const statue=originalProgress.d.querySelector('[data-id="9"]');statue.checked=true;statue.dispatchEvent(new originalProgress.w.Event('change',{bubbles:true}));
const statueReload=await open(originalProgress.w.localStorage.getItem(storageKey));assert.equal(statueReload.d.querySelector('[data-id="9"]').checked,true);
originalProgress.d.querySelector('[data-view="weekly"]').click();assert.match(originalProgress.d.querySelector('#check-nightmare').closest('.task').textContent,/14,000 Nightmare Tokens/);assert.match(originalProgress.d.querySelector('#check-nightmare').closest('.task').textContent,/Unique: Zikel’s Apparition/);
// Deployment reloads retain all fields, including hidden alt slots and stable task IDs.
const deploymentState={checks:{'route:2':true,'daily:main:festival':true,'weekly:alt6:nightmare':true},characters:{main:'Saved main',altCount:1,alts:['Visible alt','Alt 2','Alt 3','Alt 4','Alt 5','Hidden alt']},itemLevels:{main:1900.5,alt6:2100},settings:{hour:7,day:2,auto:false},periods:{daily:'2026-09-01',weekly:'2026-09-01'}};
const deploymentReload=await open(deploymentState);
assert.deepEqual(JSON.parse(deploymentReload.w.localStorage.getItem(storageKey)),deploymentState);
assert.equal(deploymentReload.d.querySelector('header a'),null);
assert.ok(deploymentReload.d.querySelector('.tracker-summary #daily-count'));
assert.ok(deploymentReload.d.querySelector('.tracker-info #reset-hour'));
deploymentReload.d.querySelector('[data-view="daily"]').click();assert.equal(deploymentReload.d.getElementById('check-festival').checked,true);
deploymentReload.d.getElementById('check-duties').checked=true;deploymentReload.d.getElementById('check-duties').dispatchEvent(new deploymentReload.w.Event('change',{bubbles:true}));
assert.deepEqual(JSON.parse(deploymentReload.w.localStorage.getItem(storageKey)),{...deploymentState,inProgress:{},timers:{},checks:{...deploymentState.checks,'daily:main:duties':true}});
const timerBrowser=await open(deploymentState);const td=timerBrowser.d,tw=timerBrowser.w;
assert.deepEqual(Array.from(tw.timerTest.defaultTimerSchedule('daily').times),[420]);
assert.equal(td.querySelector('#spawn-timers .spawn-timer').classList.contains('timer-gartua'),true);
assert.deepEqual(Array.from(tw.timerTest.defaultTimerSchedule('gartua').times),[660,1380]);
assert.deepEqual(Array.from(tw.timerTest.nextTimerTimes([660,1380],new Date('2026-10-03T11:01Z'))),[Date.parse('2026-10-03T23:00Z'),Date.parse('2026-10-04T11:00Z'),Date.parse('2026-10-04T23:00Z')]);
const gartuaBrowser=await open(deploymentState),gbd=gartuaBrowser.d,gbw=gartuaBrowser.w;
gbd.getElementById('configure-timers').click();gbd.getElementById('schedule-gartua').value='12,0';gbd.getElementById('timers-form').dispatchEvent(new gbw.Event('submit',{bubbles:true,cancelable:true}));
const gartuaSaved=JSON.parse(gbw.localStorage.getItem(storageKey));assert.deepEqual(gartuaSaved.timers,{gartua:[0,720]});assert.deepEqual(gartuaSaved.checks,deploymentState.checks);assert.deepEqual(gartuaSaved.settings,deploymentState.settings);
const gartuaReload=await open(gartuaSaved);assert.match(gartuaReload.d.getElementById('timer-schedule-gartua').textContent,/Custom.*00:00, 12:00/);

assert.match(td.getElementById('timer-schedule-daily').textContent,/In-game daily reset.*07:00/);
assert.equal(tw.timerTest.germanyDailyResetTime(new Date('2026-07-01T00:00Z')),'09:00 CEST');
assert.equal(tw.timerTest.germanyDailyResetTime(new Date('2026-12-01T00:00Z')),'08:00 CET');
assert.deepEqual(Array.from(tw.timerTest.nextTimerTimes([420],new Date('2026-10-03T07:09Z'))),[Date.parse('2026-10-04T07:00Z'),Date.parse('2026-10-05T07:00Z'),Date.parse('2026-10-06T07:00Z')]);
const customDaily=await open({...deploymentState,timers:{daily:[90]}});
assert.match(customDaily.d.getElementById('timer-schedule-daily').textContent,/Custom.*01:30/);
assert.equal(customDaily.d.getElementById('reset-hour').value,'7');

td.getElementById('configure-timers').click();td.getElementById('schedule-shugo').value='23:30, 00:30, 23:30';td.getElementById('schedule-rift').value='25:00';td.getElementById('timers-form').dispatchEvent(new tw.Event('submit',{bubbles:true,cancelable:true}));assert.match(td.getElementById('timer-error').textContent,/Rift/);assert.equal(td.getElementById('schedule-rift').getAttribute('aria-invalid'),'true');assert.match(td.getElementById('schedule-hint-rift').textContent,/25:00/);assert.deepEqual(JSON.parse(tw.localStorage.getItem(storageKey)),deploymentState);
td.getElementById('schedule-rift').value='03:00, 06:00';td.getElementById('timers-form').dispatchEvent(new tw.Event('submit',{bubbles:true,cancelable:true}));const timedState=JSON.parse(tw.localStorage.getItem(storageKey));assert.deepEqual(timedState.timers,{shugo:[30,1410],rift:[180,360]});assert.deepEqual(timedState.checks,deploymentState.checks);assert.deepEqual(timedState.settings,deploymentState.settings);
assert.deepEqual(Array.from(tw.timerTest.parseTimerTimes('1:00,2:00,3:00')),[60,120,180]);assert.deepEqual(Array.from(tw.timerTest.parseTimerTimes(' 3;1:5,02:30,1:05,\n')),[65,150,180]);assert.deepEqual(Array.from(tw.timerTest.parseTimerTimes('0,23')),[0,1380]);for(const value of ['24:00','1:60','-1','12pm','1::00'])assert.throws(()=>tw.timerTest.parseTimerTimes(value));
td.getElementById('configure-timers').click();td.getElementById('schedule-shugo').value='3:00,1:00,2:00';td.getElementById('schedule-shugo').dispatchEvent(new tw.Event('focusout',{bubbles:true}));assert.equal(td.getElementById('schedule-shugo').value,'01:00, 02:00, 03:00');assert.match(td.getElementById('schedule-hint-shugo').textContent,/Your time/);td.querySelector('[data-timer-default="shugo"]').click();assert.equal(td.getElementById('schedule-shugo').value,'');assert.match(td.getElementById('schedule-hint-shugo').textContent,/QuestLog default/);td.getElementById('cancel-timers').click();assert.deepEqual(JSON.parse(tw.localStorage.getItem(storageKey)),timedState);
td.getElementById('configure-timers').click();td.getElementById('timers-use-defaults').click();td.getElementById('timers-form').dispatchEvent(new tw.Event('submit',{bubbles:true,cancelable:true}));assert.deepEqual(JSON.parse(tw.localStorage.getItem(storageKey)).timers,{});assert.deepEqual(JSON.parse(tw.localStorage.getItem(storageKey)).checks,deploymentState.checks);
td.querySelector('.timer-shugo').open=true;td.querySelector('.timer-rift').open=true;await pause();assert.equal(td.querySelector('.timer-shugo').open,true);assert.equal(td.querySelector('.timer-rift').open,true);assert.equal(td.getElementById('timer-panel-shugo').hidden,false);assert.equal(td.getElementById('timer-panel-rift').hidden,false);assert.equal(td.getElementById('timer-panels').hidden,false);td.dispatchEvent(new tw.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(td.getElementById('timer-panels').hidden,true);
const timerReload=await open(timedState);assert.match(timerReload.d.getElementById('timer-schedule-shugo').textContent,/00:30, 23:30/);
assert.deepEqual(Array.from(tw.timerTest.nextTimerTimes([30,1410],new Date('2026-09-30T23:31:00Z'))),[Date.parse('2026-10-01T00:30Z'),Date.parse('2026-10-01T23:30Z'),Date.parse('2026-10-02T00:30Z')]);
assert.equal(tw.timerTest.timerCountdown(Date.parse('2026-10-01T00:30:00Z'),new Date('2026-09-30T23:31:01Z')),'58m 59s');
assert.equal(tw.timerTest.nextTimerTimes([30],new Date('2026-10-01T00:30:00Z'))[0],Date.parse('2026-10-01T00:30Z'));
await importFile({...backup,state:{...backup.state,timers:{shugo:[1440]}}});assert.match(d.getElementById('status').textContent,/Import rejected/);
assert.equal(tw.timerTest.activeTimerWindow({times:[0],durationMinutes:10},new Date('2026-10-01T00:05Z')).end,Date.parse('2026-10-01T00:10Z'));assert.equal(tw.timerTest.activeTimerWindow({times:[0],durationMinutes:10},new Date('2026-10-01T00:10Z')),null);
// Reward navigation/search is read-only and all old route completions retain their meaning.
const gearBrowser=await open(deploymentState);const gd=gearBrowser.d,gw=gearBrowser.w;
assert.deepEqual([...gd.querySelectorAll('.step input')].map(node=>node.dataset.id),['0','1','9','10','3','2','11','4','5','6','7','8']);
assert.equal(gd.querySelector('[data-id="2"]').checked,true);
assert.match(gd.getElementById('route-step-11').textContent,/1,600 Stage 1/);
assert.match(gd.getElementById('route-step-11').textContent,/Where: Transcendence Stage 1/);
assert.match(gd.getElementById('route-step-10').textContent,/Get accessory upgrades from green quests/);assert.match(gd.getElementById('route-step-3').textContent,/Prepare crafting and claim Draupnir armor/);assert.match(gd.getElementById('route-step-11').textContent,/Splendent Star Dragon Lord/);assert.match(gd.getElementById('route-step-8').textContent,/Splendent Star Dragon Lord/);assert.match(gd.getElementById('route-step-11').querySelector('.route-source').textContent,/Primary/);
const gearBefore=gw.localStorage.getItem(storageKey);
gd.querySelector('[data-view="rewards"]').click();
assert.equal(gd.getElementById('tab-rewards').getAttribute('aria-selected'),'true');
assert.equal(gd.querySelectorAll('.gear-stage').length,6);
assert.match(gd.querySelector('.gear-stage:last-of-type')?.textContent||gd.getElementById('gear-guide').textContent,/2,700/);
assert.match(gd.getElementById('reward-runes').textContent,/acquisition location is not given/);
assert.match(gd.getElementById('reward-horn-conquest').textContent,/2,000 label conflicts/);
let search=gd.getElementById('reward-search');search.value='Arcana';search.dispatchEvent(new gw.Event('input',{bubbles:true}));
assert.ok([...gd.querySelectorAll('.reward-card')].filter(card=>!card.hidden).length>0);
assert.equal(gd.getElementById('reward-stage1').hidden,false);assert.equal(gd.getElementById('reward-nightmare').hidden,true);
search.value='not-an-existing-reward';search.dispatchEvent(new gw.Event('input',{bubbles:true}));assert.equal(gd.getElementById('reward-empty').hidden,false);
search.value='';search.dispatchEvent(new gw.Event('input',{bubbles:true}));assert.equal(gd.querySelectorAll('.reward-card[hidden]').length,0);
gd.querySelector('[data-view="daily"]').click();gd.querySelector('[data-reward-target="shugo"]').click();assert.equal(gd.getElementById('tab-rewards').getAttribute('aria-selected'),'true');assert.match(gd.getElementById('reward-shugo').textContent,/Daevanion Crystals first/);
assert.equal(gw.localStorage.getItem(storageKey),gearBefore);
gd.querySelector('[data-view="route"]').click();assert.equal(gd.querySelector('[data-id="2"]').checked,true);
const guideData=JSON.parse(sourceScripts[0].replace(/^const DATA = /,'').trim().replace(/;$/,''));
const knownRewards=new Set(guideData.rewardSources.map(item=>item.id));
for(const stage of guideData.gearGuide.stages)assert.ok(Number.isFinite(stage.chartTotal));
const craftingRows=guideData.gearGuide.stages.flatMap(stage=>stage.rows).filter(row=>/Splendent Star Dragon Lord/.test(row[0]));
assert.equal(craftingRows.length,3);assert.ok(craftingRows.every(row=>row[1]===null),'Corrected crafting gains must not reuse the old tier estimates');
assert.doesNotMatch(sourceScripts[0],/White Dragon|Dark Dragon|Wise Dragon|Ebony Dragon/);
assert.equal(knownRewards.size,guideData.rewardSources.length);
for(const milestone of guideData.route)for(const id of milestone[7])assert.ok(knownRewards.has(id),'Unknown route reward '+id);
for(const group of ['daily','weekly'])for(const task of guideData[group])if(task[6]?.rewardTarget)assert.ok(knownRewards.has(task[6].rewardTarget));
// In-progress status is independent per character and survives reloads/backups.
const progressBrowser=await open(deploymentState),pd=progressBrowser.d,pw=progressBrowser.w;
const progressState=()=>JSON.parse(pw.localStorage.getItem(storageKey));
const visit=group=>pd.querySelector('[data-view="'+group+'"]').click();
function toggle(id,value){const field=pd.getElementById(id);field.checked=value;field.dispatchEvent(new pw.Event('change',{bubbles:true}))}
function selectCharacter(id){pd.getElementById('character').value=id;pd.getElementById('character').dispatchEvent(new pw.Event('change'))}
visit('daily');assert.equal(pd.querySelectorAll('[data-progress-group="daily"]').length,9);
assert.equal(pd.getElementById('daily-in-progress').textContent,'0 in progress');
assert.equal(pd.getElementById('daily-in-progress-tasks').hidden,true);
toggle('progress-festival',true);
assert.equal(progressState().checks['daily:main:festival'],undefined);
assert.equal(progressState().inProgress['daily:main:festival'],true);
assert.equal(pd.getElementById('daily-count').textContent,'0 / 9');
assert.equal(pd.getElementById('daily-in-progress').textContent,'1 in progress');
assert.equal(pd.getElementById('daily-in-progress-tasks').hidden,false);
assert.match(pd.getElementById('daily-in-progress-tasks').textContent,/Shugo Festival/);
assert.match(pd.getElementById('daily-next').textContent,/Shugo Festival/);
assert.equal(pd.getElementById('check-festival').checked,false);
assert.equal(pd.getElementById('progress-festival').closest('.task').classList.contains('in-progress'),true);
assert.match(pd.querySelector('.checklist-status').textContent,/1 in progress/);
toggle('check-festival',true);
assert.equal(progressState().inProgress['daily:main:festival'],undefined);
assert.equal(pd.getElementById('progress-festival').checked,false);
assert.equal(pd.getElementById('daily-count').textContent,'1 / 9');
assert.equal(pd.getElementById('daily-in-progress').textContent,'0 in progress');
toggle('progress-festival',true);toggle('progress-festival',false);
assert.equal(progressState().inProgress['daily:main:festival'],undefined);
assert.equal(pd.getElementById('check-festival').checked,false);
toggle('progress-festival',true);selectCharacter('alt1');
assert.equal(pd.getElementById('daily-in-progress').textContent,'0 in progress');
toggle('progress-duties',true);visit('weekly');
assert.equal(pd.querySelectorAll('[data-progress-group="weekly"]').length,8);
toggle('progress-nightmare',true);
assert.equal(pd.getElementById('weekly-in-progress').textContent,'1 in progress');
assert.match(pd.getElementById('weekly-in-progress-tasks').textContent,/Nightmare/);
selectCharacter('main');assert.equal(pd.getElementById('weekly-in-progress').textContent,'0 in progress');
assert.equal(pd.getElementById('daily-in-progress').textContent,'1 in progress');
const activeSaved=progressState(),activeReload=await open(activeSaved);
assert.equal(activeReload.d.getElementById('daily-in-progress').textContent,'1 in progress');
activeReload.d.querySelector('[data-view="daily"]').click();assert.equal(activeReload.d.getElementById('progress-festival').checked,true);
let progressBlob;pw.URL.createObjectURL=blob=>{progressBlob=blob;return 'blob:progress-backup'};pw.URL.revokeObjectURL=()=>{};
pd.getElementById('export-data').click();const progressBackup=JSON.parse(await progressBlob.text());
assert.equal(progressBackup.version,2);assert.deepEqual(progressBackup.state.inProgress,activeSaved.inProgress);
async function importProgress(payload){const file=new pw.File([JSON.stringify(payload)],'progress.json',{type:'application/json'});Object.defineProperty(pd.getElementById('import-file'),'files',{value:[file],configurable:true});pd.getElementById('import-file').dispatchEvent(new pw.Event('change'));await pause()}
visit('daily');pd.querySelector('[data-reset="daily"]').click();pd.getElementById('confirm-reset').click();
assert.equal(progressState().inProgress['daily:main:festival'],undefined);
assert.equal(progressState().inProgress['daily:alt1:duties'],true);
assert.equal(progressState().inProgress['weekly:alt1:nightmare'],true);
assert.equal(progressState().checks['weekly:alt6:nightmare'],true);
assert.equal(progressState().checks['route:2'],true);
await importProgress(progressBackup);pd.getElementById('confirm-import').click();
assert.deepEqual(progressState().inProgress,activeSaved.inProgress);
assert.equal(pd.getElementById('daily-in-progress').textContent,'1 in progress');
const validProgress=pw.localStorage.getItem(storageKey);
for(const bad of [null,[],{'route:2':true},{'daily:main:duties':'true'}]){
  await importProgress({...progressBackup,state:{...activeSaved,inProgress:bad}});
  assert.match(pd.getElementById('status').textContent,/Import rejected/);
  assert.equal(pw.localStorage.getItem(storageKey),validProgress);
}
const conflicting=await open({...activeSaved,checks:{...activeSaved.checks,'daily:main:festival':true}});
assert.equal(conflicting.d.getElementById('daily-in-progress').textContent,'0 in progress');
conflicting.d.querySelector('[data-view="daily"]').click();assert.equal(conflicting.d.getElementById('progress-festival').checked,false);assert.equal(conflicting.d.getElementById('check-festival').checked,true);
const activeReset=await open({...activeSaved,settings:{hour:0,day:3,auto:true},periods:{daily:'2020-01-01',weekly:'2020-01-01'}});
const autoProgress=JSON.parse(activeReset.w.localStorage.getItem(storageKey));
assert.deepEqual(autoProgress.inProgress,{});assert.deepEqual(autoProgress.checks,{'route:2':true});
const dailyOnlyReset=await open({...activeSaved,settings:{hour:0,day:3,auto:true},periods:{daily:'2020-01-01'}});
const dailyOnly=JSON.parse(dailyOnlyReset.w.localStorage.getItem(storageKey));
assert.equal(dailyOnly.inProgress['daily:main:festival'],undefined);assert.equal(dailyOnly.inProgress['weekly:alt1:nightmare'],true);
pw.dispatchEvent(new pw.StorageEvent('storage',{key:storageKey,newValue:JSON.stringify({...activeSaved,inProgress:{'daily:main:duties':true}})}));
assert.equal(pd.getElementById('daily-in-progress').textContent,'1 in progress');assert.match(pd.getElementById('daily-in-progress-tasks').textContent,/Duty quests/);
const corrupt=await open('{broken');assert.equal(corrupt.w.localStorage.getItem(storageKey),'{broken');assert.equal(corrupt.d.getElementById('import-data').disabled,false);
const storage=w.localStorage;Object.defineProperty(w,'localStorage',{configurable:true,value:{getItem:storage.getItem.bind(storage),setItem(){throw Error('quota')}}});d.querySelector('[data-view="route"]').click();input=d.querySelector('[data-group="route"]');input.checked=true;input.dispatchEvent(new w.Event('change',{bubbles:true}));assert.match(d.getElementById('status').textContent,/storage is unavailable/);assert.equal(d.getElementById('export-data').disabled,false);Object.defineProperty(w,'localStorage',{configurable:true,value:storage});d.getElementById('retry').click();assert.match(d.getElementById('status').textContent,/Saved/);
assert.equal(requests.length,0);for(const win of windows){await win.happyDOM.abort();win.close()}console.log('Passed: local persistence, names and alt counts, per-character checklists and in-progress status, safe text, backup import/export, invalid imports, resets and storage failures.');
